package kitty

import (
	"os"

	"kittypaper/internal/platform/filex"
)

func EnsureGenerated(path string) error {
	if _, err := os.Stat(path); err == nil {
		return nil
	} else if !os.IsNotExist(err) {
		return err
	}
	return filex.WriteFileAtomic(path, []byte("# Generated by kittypaper. Do not edit.\n"), 0o644)
}
