package kitty

import (
	"context"
	"fmt"
	"path/filepath"

	"kittypaper/internal/adapters/infra/config"
	"kittypaper/internal/platform/filex"
)

type Writer struct {
	GeneratedConfPath string
	Layout            string
	Tint              float64
	Opacity           float64
}

func (w Writer) WriteBackgroundConfig(ctx context.Context, wallpaperPath string) error {
	_ = ctx
	layout := w.Layout
	if layout == "" {
		layout = "scaled"
	}
	tint := w.Tint
	if tint < 0 || tint > 1 {
		tint = config.DefaultBackgroundTint
	}
	opacity := w.Opacity
	if opacity < 0 || opacity > 1 {
		opacity = config.DefaultBackgroundOpacity
	}

	abs := wallpaperPath
	if cleaned, err := filepath.Abs(wallpaperPath); err == nil {
		abs = cleaned
	}

	// Kitty accepts bare paths; avoid quotes that some parsers mishandle.
	content := fmt.Sprintf(
		"# Generated by kittypaper. Do not edit.\nbackground_image %s\nbackground_image_layout %s\nbackground_image_linear yes\nbackground_tint %.2f\nbackground_opacity %.2f\n",
		abs,
		layout,
		tint,
		opacity,
	)
	return filex.WriteFileAtomic(w.GeneratedConfPath, []byte(content), 0o644)
}
